on:
  push:
    branches:
      - "patch-release"


name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g @vscode/vsce
      - run: npm install
      - run: "vsce publish patch --yarn"
      - env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}

