name: "Close finished milestones"
on:
  issues:
    types: [opened, deleted, closed, reopened, milestoned, demilestoned]
  pull_request:
    types: [opened, closed, reopened]

env:
  GH_TOKEN: ${{ github.token }}
jobs:
  milestone-closer:
    if: github.event.milestone.open_issues == 0
    runs-on: ubuntu-latest
    steps:
      - name: Close a milestone
        run: |
          set -x
          gh api -X PATCH repos/${GITHUB_REPOSITORY}/milestones/${{ github.event.milestone.number }} -f state=closed
